export const lightTheme = {
  background: "#fff",
  backgroundReverse: "#222",
  grayButton: "#eaeaea",
  colorReverse: "#fff",
  color: "#222",
  headerBackground: "hsla(0, 0%, 100%, 0.75)",
  headerAndMenuBorder: "1px solid #EAEAEA",
  backgroundModal: "rgb(250, 250, 250, 0.85)",
  contactButtonBorder: "1.5px solid #222",
  contactButtonColor: "#222",
  contactButtonBackground: '#222',
  footerBackground: '#FAFAFA',
  activeColor: '#0070f5',
  descColor: "#757575",
  activeButton: '#0070f5',
  activeButtonColor: '#fff',
  labelColor: '#888'
};

export const darkTheme = {
  background: "#000",
  backgroundReverse: "#fff",
  grayButton: "#eaeaea",
  colorReverse: "#000",
  color: "#fff",
  headerBackground: "hsl(0deg 0% 0% / 50%)",
  headerAndMenuBorder: "0.1px solid rgb(72, 72, 72)",
  backgroundModal: "rgb(0, 0, 0, 0.85)",
  contactButtonBorder: "1.5px solid #fff",
  menuBorder: '0.1px solid rgb(57, 57, 57)',
  contactButtonColor: "#fff",
  contactButtonBackground: '#fff',
  footerBackground: '#000',
  activeColor: '#fc6d26',
  descColor: "#888",
  activeButton: '#222',
  activeButtonColor: '#fff',
  labelColor: '#fff'
};
